rn.mods.basegame =
{
	description = "Base game content for Red Nightmare",
	prefabs = {},
	levels = {},
	spells = {},
	buffs = {},
	items = {}
}

require("basegame/prefabs/mouse_controlled")
require("basegame/prefabs/keyboard_controlled")
require("basegame/prefabs/faction")
require("basegame/prefabs/light_emitter")
require("basegame/prefabs/sticky")
require("basegame/prefabs/sprite")
require("basegame/prefabs/bipedal")
require("basegame/prefabs/bipedal_human")
require("basegame/prefabs/bipedal_maker")
require("basegame/prefabs/bipedal_ogre")
require("basegame/prefabs/bipedal_skeleton")
require("basegame/prefabs/magicbolt")
require("basegame/prefabs/allure_of_flame")
require("basegame/prefabs/cast_buildup")
require("basegame/prefabs/combat_stats")
require("basegame/prefabs/loot_drop")
require("basegame/prefabs/magic_barrier")
require("basegame/prefabs/obstacle")
require("basegame/prefabs/wall")
require("basegame/prefabs/dirt_path")
require("basegame/prefabs/invisible_wall")
require("basegame/prefabs/loot_chest")
require("basegame/prefabs/text")
require("basegame/prefabs/floating_combat_text")
require("basegame/prefabs/health_bar")
require("basegame/prefabs/melee_swing_area")
require("basegame/prefabs/consecration_effect")
require("basegame/prefabs/enemy_ai")
require("basegame/prefabs/melee_monster")
require("basegame/prefabs/zombie")
require("basegame/prefabs/skeleton")
require("basegame/prefabs/spell_drop")
require("basegame/prefabs/spell_slots")
require("basegame/prefabs/spellsteal_projectile")
require("basegame/prefabs/elemental")
require("basegame/prefabs/portal")

require("basegame/prefabs/players/player")

require("basegame/prefabs/npcs/boss_rathallus")

require("basegame/prefabs/weapon_models/axe")
require("basegame/prefabs/weapon_models/lightbringer")
require("basegame/prefabs/weapon_models/morning_star")
require("basegame/prefabs/weapon_models/maul")
require("basegame/prefabs/weapon_models/small_shield")
require("basegame/prefabs/weapon_models/sword")
require("basegame/prefabs/weapon_models/sword2h")
require("basegame/prefabs/weapon_models/torch")
require("basegame/prefabs/weapon_models/staff")

require("basegame/spells/melee")
require("basegame/spells/allure_of_flames")
require("basegame/spells/charge")
require("basegame/spells/consecrate")
require("basegame/spells/enrage")
require("basegame/spells/savage_kick")
require("basegame/spells/cruel_lie")
require("basegame/spells/deadly_throw")
require("basegame/spells/equivocation")
require("basegame/spells/firestorm")
require("basegame/spells/flash_of_light")
require("basegame/spells/harsh_truth")
require("basegame/spells/lesser_magicbolt")
require("basegame/spells/icicle")
require("basegame/spells/sacred_shield")
require("basegame/spells/spellsteal")
require("basegame/spells/summon_zombie")
require("basegame/spells/zombie_devour")
require("basegame/spells/zombie_swipe")

require("basegame/buffs/charge_rush")
require("basegame/buffs/chilled")
require("basegame/buffs/enraged")
require("basegame/buffs/ignite")
require("basegame/buffs/sacred_shield_absorb")
require("basegame/buffs/spell_stolen_from")
require("basegame/buffs/spell_stolen_to")
require("basegame/buffs/timed_despawn")

require("basegame/items/armour_sets/metal_armour_set_base")
require("basegame/items/armour_sets/iron_armour_set")
require("basegame/items/armour_sets/mythril_armour_set")
require("basegame/items/armour_sets/steel_armour_set")
require("basegame/items/armour_sets/radiant_armour_set")

require("basegame/items/facial_hair/full_beard")
require("basegame/items/facial_hair/walrus")

require("basegame/items/basic_torch")
require("basegame/items/blazing_staff")
require("basegame/items/elemental_gear")
require("basegame/items/fiery_hauberk")
require("basegame/items/fire_staff")
require("basegame/items/holy_water_sprinkler")
require("basegame/items/insin")
require("basegame/items/peasant_pants")
require("basegame/items/peasant_shirt")
require("basegame/items/elemental_circlet")

require("basegame/levels/startscreen")
require("basegame/levels/clans_camp")
require("basegame/levels/dev0")
require("basegame/levels/devproc0")