#ifndef REDNIGHTMARE_IMAGES_HPP
#define REDNIGHTMARE_IMAGES_HPP
#include "tz/gl/resource.hpp"

namespace game
{
	// See top of images.cpp for implementation of TextureIDs. Each textureid corresponds to a compile-time loaded png blob which is converted into an image_resource at runtime.
	enum class TextureID : std::uint32_t
	{
		Missing,
		Invisible,
		Smooth_Normals,
		PlayerAkhara_Cast0,
		PlayerAkhara_Cast1,
		PlayerAkhara_Cast2,
		PlayerAkhara_Cast3,
		PlayerAkhara_Cast4,
		PlayerAkhara_Cast5,
		PlayerAkhara_Cast6,
		PlayerAkhara_Cast7,
		PlayerAkhara_Death00,
		PlayerAkhara_Death01,
		PlayerAkhara_Death02,
		PlayerAkhara_Death03,
		PlayerAkhara_Death04,
		PlayerAkhara_Death05,
		PlayerAkhara_Death06,
		PlayerAkhara_Death07,
		PlayerAkhara_Death08,
		PlayerAkhara_Death09,
		PlayerAkhara_Death10,
		PlayerAkhara_Death11,
		PlayerAkhara_Down0,
		PlayerAkhara_Down1,
		PlayerAkhara_Down2,
		PlayerAkhara_Down3,
		PlayerAkhara_EndCast0,
		PlayerAkhara_EndCast1,
		PlayerAkhara_EndCast2,
		PlayerAkhara_EndCast3,
		PlayerAkhara_EndCast4,
		PlayerAkhara_EndCast5,
		PlayerAkhara_Idle0,
		PlayerAkhara_Idle1,
		PlayerAkhara_Side0,
		PlayerAkhara_Side1,
		PlayerAkhara_Side2,
		PlayerAkhara_Side3,
		PlayerAkhara_Up0,
		PlayerAkhara_Up1,
		PlayerAkhara_Up2,
		PlayerAkhara_Up3,
		GhostZombie_Death_0,
		GhostZombie_Death_1,
		GhostZombie_Death_2,
		GhostZombie_Death_3,
		GhostZombie_Down_0,
		GhostZombie_Down_1,
		GhostZombie_Down_2,
		GhostZombie_Down_3,
		GhostZombie_Idle_0,
		GhostZombie_Idle_1,
		GhostZombie_Side_0,
		GhostZombie_Side_1,
		GhostZombie_Side_2,
		GhostZombie_Side_3,
		GhostZombie_Up_0,
		GhostZombie_Up_1,
		GhostZombie_Up_2,
		GhostZombie_Up_3,
		GhostMJZombie_Death_0,
		GhostMJZombie_Death_1,
		GhostMJZombie_Death_2,
		GhostMJZombie_Death_3,
		GhostMJZombie_Down_0,
		GhostMJZombie_Down_1,
		GhostMJZombie_Down_2,
		GhostMJZombie_Down_3,
		GhostMJZombie_Idle_0,
		GhostMJZombie_Idle_1,
		GhostMJZombie_Side_0,
		GhostMJZombie_Side_1,
		GhostMJZombie_Side_2,
		GhostMJZombie_Side_3,
		GhostMJZombie_Up_0,
		GhostMJZombie_Up_1,
		GhostMJZombie_Up_2,
		GhostMJZombie_Up_3,
		GhostBanshee_Idle_0,
		GhostBanshee_Idle_1,
		GhostBanshee_Death_0,
		GhostBanshee_Death_1,
		GhostBanshee_Death_2,
		GhostBanshee_Death_3,
		GhostBanshee_Death_4,
		GhostBanshee_Death_5,
		GhostBanshee_Death_6,
		GhostBanshee_Death_7,
		GhostBanshee_Death_8,
		GhostBanshee_Death_9,
		GhostBanshee_Death_10,
		GhostBanshee_Death_11,

		PlayerAkhara_Default_Fireball,
		PlayerAkhara_Default_Fireball_Particles_0,
		PlayerAkhara_Default_Fireball_Particles_1,
		PlayerAkhara_Default_Fireball_Particles_2,
		PlayerAkhara_Default_Fireball_Particles_3,
		PlayerAkhara_Default_Fireball_Particles_4,
		PlayerAkhara_Default_Fireball_Particles_5,
		PlayerAkhara_Default_Fireball_Particles_6,

		BlockBreak_0,
		BlockBreak_1,
		BlockBreak_2,
		BlockBreak_3,
		BlockBreak_4,
		BlockBreak_5,
		BlockBreak_6,
		BlockBreak_7,
		BlockBreak_8,
		BlockBreak_9,
		BlockBreak_10,
		BlockBreak_11,
		BlockBreak_12,
		BlockBreak_13,

		BloodSplatter_0,
		BloodSplatter_1,
		BloodSplatter_2,
		BloodSplatter_3,
		BloodSplatter_4,
		BloodSplatter_5,
		BloodSplatter_6,
		BloodSplatter_7,

		FireExplosion_0,
		FireExplosion_1,
		FireExplosion_2,
		FireExplosion_3,
		FireExplosion_4,
		FireExplosion_5,
		FireExplosion_6,
		Nightmare_Dead,
		Nightmare_Down_1,
		Nightmare_Down_2,
		Nightmare_Down_3,
		Nightmare_Dying_1,
		Nightmare_Dying_2,
		Nightmare_Dying_3,
		Nightmare_Dying_4,
		Nightmare_Dying_5,
		Nightmare_Dying_6,
		Nightmare_Dying_7,
		Nightmare_Dying_8,
		Nightmare_Dying_9,
		Nightmare_Dying_10,
		Nightmare_Idle_1,
		Nightmare_Idle_2,
		Nightmare_Side_1,
		Nightmare_Side_2,
		Nightmare_Side_3,
		Nightmare_Special,
		Nightmare_Up_1,
		Nightmare_Up_2,
		Nightmare_Up_3,

		Material_Stone,
		Material_Stone_Normal,

		Gui_Healthbar_Empty,
		Scenery_Gravestone_0,
		Scenery_Gravestone_1,
		Interactable_Torch_Off,
		Downwards_Trapdoor,
		Interactable_Stone_Stairs_Down_NX,
		Interactable_Stone_Stairs_Up_NX,
		Interactable_Stone_Stairs_Down_PY,
		Interactable_Stone_Stairs_Up_PY,

		Powerup_Sprint_0,
		Powerup_Sprint_1,
		Powerup_Sprint_2,

		DevLevel1_Backdrop,
		DevLevel1_Backdrop_Normal,
		Grass_Generic_Backdrop,
		Grass_Generic_Backdrop_Normal,
		Snow_Generic_Backdrop,
		Dungeon_Floor_Generic_Backdrop,
		Dungeon_Floor_Generic_Backdrop_Normal,

		Count
	};

	tz::gl::image_resource load_image(TextureID texid);
	tz::gl::image_resource load_image_data(std::string_view img_file_data);
	TextureID get_normal_map_for(TextureID tex);
}

#endif // REDNIGHTMARE_IMAGES_HPP
